export const products = [
  {
    id: 1,
    name: "Wireless Mouse",
    price: 499,
    category: "Electronics",
    inStock: true,
  },
  {
    id: 2,
    name: "Bluetooth Headphones",
    price: 1299,
    category: "Electronics",
    inStock: true,
  },
  {
    id: 3,
    name: "Smart Watch",
    price: 3499,
    category: "Electronics",
    inStock: false,
  },
  {
    id: 4,
    name: "Laptop Stand",
    price: 899,
    category: "Accessories",
    inStock: true,
  },
  {
    id: 5,
    name: "Gaming Keyboard",
    price: 1999,
    category: "Electronics",
    inStock: true,
  },
  { id: 6, name: "Desk Lamp", price: 699, category: "Home", inStock: true },
  {
    id: 7,
    name: "Water Bottle",
    price: 299,
    category: "Lifestyle",
    inStock: false,
  },
  {
    id: 8,
    name: "Backpack",
    price: 1499,
    category: "Lifestyle",
    inStock: true,
  },
  {
    id: 9,
    name: "Notebook",
    price: 199,
    category: "Stationery",
    inStock: true,
  },
  {
    id: 10,
    name: "Pen Set",
    price: 149,
    category: "Stationery",
    inStock: true,
  },
  {
    id: 11,
    name: "Sunglasses",
    price: 799,
    category: "Accessories",
    inStock: false,
  },
  { id: 12, name: "Shoes", price: 2499, category: "Lifestyle", inStock: true },
  { id: 13, name: "T-shirt", price: 599, category: "Clothing", inStock: true },
  { id: 14, name: "Jeans", price: 1299, category: "Clothing", inStock: true },
  { id: 15, name: "Coffee Mug", price: 399, category: "Home", inStock: true },
  {
    id: 16,
    name: "Headphone Stand",
    price: 699,
    category: "Accessories",
    inStock: true,
  },
];
